paths:
  /api/products/:
    get:
      summary: Get all products
      tags:
      - Products
      responses:
        "200":
          description: Get all products succesfully from database
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#components/schemas/Product'
        "500":
          description: Internal server error
    post:
      summary: Create a new product
      tags:
        - Products
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#components/requestBodies/createProduct'
      responses:
        "201":
          description: New product added to database succesfully
          content:
            application/json:
              schema:
                type: object
                $ref: '#components/schemas/Product'
        "400":
          description: Some of the required properties are missing
        "500":
          description: Internal server error
  /api/products/{pid}:
    get:
      summary: Get a single product specified by its Id
      tags:
        - Products
      parameters:
      - name: pid
        in: path
        required: true
        description: Product Id
        schema:
         $type: string
      responses:
        "200":
          description: Get the specified product successfully from database
          content: 
            application/json:
              schema:
                $ref: '#components/schemas/Product'
        "400":
          description: Missing product Id on the request
        "404":
          description: No product found with the specified Id
        "500": 
          description: Internal Server Error
    put:
      summary: Update a product properties values using its Id
      tags:
        - Products
      parameters:
      - name: pid
        in: path
        required: true
        description: Product Id
        schema:
          $type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#components/requestBodies/updateProduct'
      responses:
        "200":
          description: Specified product update successfully
          content:
            application/json:
              schema:
              type: object
              $ref: '#components/schemas/Product'
        "400":
          description: Not property or Id specified
        "404":
          description: Not product found for the specified Id
        "500":
          description: Internal server error
    delete:
      summary: Delete a product specified by its Id
      tags:
        - Products
      parameters:
      - name: pid
        in: path
        required: true
        description: Product Id
        schema:
          $type: string
      responses:
        "200":
          description: Specified product deleted successfully
          content:
            application/json:
              schema:
                type: object
                $ref: '#components/schemas/Product'
        "400":
          description: Not Id specified
        "403":
          description: Can not access this resource if you are not the products owner
        "404":
          description: Not product found for the specified Id
        "500":
          description: Internal server error


components:
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: ObjectId
          description: Autogenerated Mongo Id
        title:
          type: string
          description: Products title
        description:
          type: string
          description: Products description    
        code:
          type: string
          description: Unique code for product
        price:
          type: number
          description: Products price
        stock:
          type: number
          description: Products available amount
        category:
          type: string
          description: Products category
        status:
          type: boolean
          description: Defines if a product is available right now or not
        thumbnails:
          type: array
          description: Products images
          item:
            type: file
        owner:
          type: string
          description: Products owner
      example:
        _id: ObjectId("abc123abc123")
        title: Nintendo Ds
        description: this is a portable game console
        code: nintendods123
        price: 666
        stock: 10
        category: game
        status: true
        thumbnails: []
        owner: Mauricio
  requestBodies:
    updateProduct:
      type: object
      properties:
        title:
          type: string
          description: Products title
        description:
          type: string
          description: Products description
        code:
          type: string
          description: Unique code for product
        price:
          type: number
          description: Products price
        stock:
          type: number
          description: Products available amount
        category:
          type: string
          description: Products category
        thumbnails:
          type: array
          description: Products images
          item:
            type: file
        owner:
          type: string
          description: Products owner  
      example:
        _id: ObjectId("abc123abc123")
        title: Nintendo Ds
        description: this is a portable game console
        code: nintendods123
        price: 666
        stock: 10
        category: game
        thumbnails: []
        owner: Mauricio
    createProduct:
      type: object
      properties:
        title:
          type: string
          description: Products title
        description:
          type: string
          description: Products description
        code:
          type: string
          description: Unique code for product
        price:
          type: number
          description: Products price
        stock:
          type: number
          description: Products available amount
        category:
          type: string
          description: Products category
        thumbnails:
          type: array
          description: Products images
          item:
            type: file
        owner:
          type: string
          description: Products owner  
      example:
        _id: ObjectId("abc123abc123")
        title: Nintendo Ds
        description: this is a portable game console
        code: nintendods123
        price: 666
        stock: 10
        category: game
        thumbnails: []
        owner: Mauricio    
